sensor:
- platform: toptronic
  name: "Valeur r\xE9elle pi\xE8ce"
  device_type: BD
  device_addr: ${TT_BD_addr}
  function_group: 83
  function_number: 0
  datapoint: 0
  id: BD_83_0_0
  type: S16
  unit_of_measurement: "\xB0C"
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
