sensor:
- platform: toptronic
  name: Raum-Ist
  device_type: BM
  device_addr: ${TT_BM_addr}
  function_group: 83
  function_number: 0
  datapoint: 0
  id: BM_83_0_0
  type: S16
  unit_of_measurement: "\xB0C"
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
